version: "3"
networks:
  grafana:
  loki:

services:
  tempo:
    image: grafana/tempo:latest
    # platform: linux/amd64
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./shared/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    networks:
      - grafana

  k6-tracing:
    platform: linux/amd64
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
    environment:
      - ENDPOINT=tempo:4317
    restart: always
    depends_on:
      - tempo
    networks:
      - grafana

  prometheus:
    image: prom/prometheus:latest
    # platform: linux/amd64
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./shared/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - grafana

  grafana:
    image: grafana/grafana:latest
    # platform: linux/amd64
    volumes:
      - ./shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    networks:
      - grafana
      - loki
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:main
    # platform: linux/amd64
    volumes:
      - ./etc/loki/local-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./shared/promtail-local-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - loki


  agent:
    platform: linux/amd64
    image: grafana/agent:latest
    volumes:
      - ./agent/config.river:/etc/agent/config.river
    ports:
      - 12345:12345
      - 8080:8080
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/agent/config.river
    environment:
      - AGENT_MODE=flow
      - HOSTNAME=agent
    networks:
      - loki
      - grafana

  # agent:
  #   platform: linux/amd64
  #   image: grafana/agent:latest
  #   volumes:
  #     - ./agent/config.yaml:/etc/agent-config/agent.yaml
  #     - ./agent/config.river:/etc/grafana-agent/config.river
  #   entrypoint:
  #     - /bin/grafana-agent
  #     - -server.http.address=0.0.0.0:12345
  #     - -config.file=/etc/agent-config/agent.yaml
  #     - -metrics.wal-directory=/tmp/agent/wal
  #     - -enable-features=integrations-next
  #     - -config.expand-env
  #     - -config.enable-read-api
  #   environment:
  #     HOSTNAME: agent
  #     AGENT_MODE: flow
  #     LOKI_HOST: loki:3100
  #     # TEMPO_HOST: tempo:4317
  #   ports:
  #     - "12345:12345"
  #   depends_on:
  #     - tempo


  
