services:
  redis-master-1:
    container_name: redis-master-1
    image: redis:6.2.3
    network_mode: "host"   
    command: redis-server /etc/redis.conf   
    volumes: 
    - ./redis.conf:/etc/redis.conf
    restart: always
    ports:
    - 6379:6379